/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CXgfgDQMehG
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function portfolio() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="flex flex-col shrink-0">
        <div className="py-4 bg-gray-900 text-gray-50">
          <div className="container flex items-center justify-between px-4 md:px-6 space-y-2 md:space-y-0">
            <Link className="flex items-center space-2" href="#">
              <SquareIcon className="h-6 w-6" />
              <span className="font-semibold">Portfolio</span>
            </Link>
            <nav className="items-center gap-4 sm:gap-6">
              <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                Projects
              </Link>
              <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                About
              </Link>
              <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
                Contact
              </Link>
            </nav>
          </div>
        </div>
      </header>
      <main className="grid gap-12 lg:gap-24">
        <div className="mx-auto max-w-6xl space-y-4 px-4 md:px-6">
          <div className="space-y-2 text-center">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">My Projects</h1>
            <p className="mx-auto max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I love to create beautiful and useful things. Here are some of my favorite projects.
            </p>
          </div>
          <div className="grid gap-12 md:gap-8 lg:gap-16">
            <div className="grid gap-4 md:grid-cols-3 md:gap-8">
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project One</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project Two</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project Three</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
            </div>
            <div className="grid gap-4 md:grid-cols-3 md:gap-8">
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project Four</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project Five</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
              <div className="space-y-2">
                <img
                  alt="Project hero"
                  className="overflow-hidden rounded-xl object-cover aspect-video"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="space-y-1">
                  <h3 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Project Six</h3>
                  <p className="text-gray-500 dark:text-gray-400">Description</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-12 md:gap-8 lg:gap-16">
          <div className="mx-auto max-w-6xl space-y-4 px-4 md:px-6">
            <div className="space-y-2 text-center">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">My Skills</h2>
              <p className="mx-auto max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                I'm skilled in a variety of areas. Here are a few of my top skills.
              </p>
            </div>
            <div className="grid gap-4 md:gap-8 justify-items-center">
              <div className="flex flex-col items-center gap-2">
                <CodeIcon className="h-10 w-10" />
                <span className="text-lg font-semibold">Web Development</span>
                <p className="text-center text-gray-500 dark:text-gray-400">
                  I create beautiful and functional websites using the latest technologies.
                </p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <SmileIcon className="h-10 w-10" />
                <span className="text-lg font-semibold">UX Design</span>
                <p className="text-center text-gray-500 dark:text-gray-400">
                  I focus on creating a seamless and enjoyable user experience for all my projects.
                </p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <DatabaseIcon className="h-10 w-10" />
                <span className="text-lg font-semibold">Database Management</span>
                <p className="text-center text-gray-500 dark:text-gray-400">
                  I'm skilled in managing databases to ensure data is secure and accessible.
                </p>
              </div>
              <div className="flex flex-col items-center gap-2">
                <SmartphoneIcon className="h-10 w-10" />
                <span className="text-lg font-semibold">Mobile Development</span>
                <p className="text-center text-gray-500 dark:text-gray-400">
                  I create mobile apps that are responsive and user-friendly.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="grid gap-12 md:gap-8 lg:gap-16">
          <div className="mx-auto max-w-3xl space-y-4 px-4 md:px-6">
            <div className="space-y-2 text-center">
              <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Contact Me</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Want to work together? Fill out the form below or email me at
                <div />.{"\n"}
              </p>
            </div>
            <div className="mx-auto w-full max-w-[550px] space-y-2">
              <div className="space-y-4">
                <div className="grid gap-4 sm:grid-cols-2">
                  <Input placeholder="First Name" required type="text" />
                  <Input placeholder="Last Name" required type="text" />
                </div>
                <Input className="max-w-none" placeholder="Email" required type="email" />
                <Textarea className="max-w-none" placeholder="Your Message" required />
                <Button type="submit">Submit</Button>
              </div>
              <div className="space-y-4">
                <div className="text-center">
                  <h2 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Professional Links</h2>
                  <div className="grid gap-4">
                    <Link className="text-lg font-semibold hover:underline underline-offset-4" href="#">
                      LinkedIn
                    </Link>
                    <Link className="text-lg font-semibold hover:underline underline-offset-4" href="#">
                      GitHub
                    </Link>
                    <Link className="text-lg font-semibold hover:underline underline-offset-4" href="#">
                      GitLab
                    </Link>
                    <Link className="text-lg font-semibold hover:underline underline-offset-4" href="#">
                      Download CV
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function SquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function SmartphoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
